---
driver:
  name: vagrant
  customize: {cpus: 2, memory: 1024}
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]
    - ["forwarded_port", {guest: 5050, host: 5050}]

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: centos-7.2
  - name: centos-6.8
  - name: ubuntu-16.04
  - name: ubuntu-14.04
suites:
  - name: default
    run_list:
      - recipe[mesos::master]
      - recipe[mesos::slave]
      - recipe[marathon]
      - recipe[marathon::service]
    attributes:
      marathon:
        flags:  # run Marathon without ZooKeeper
          ha: false
          master: 'localhost:5050'
          internal_store_backend: 'mem'
